[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "polo-sdk-python"
authors = [{name = "Christopher Gamache", email = "chris.gamache@poloniex.com"}]
dynamic = ["version", "description"]
